const SITE_ORIGIN = 'https://www.ffliveplay.com';

const ADSENSE_PUBLISHER_ID = 'pub-PASTE_REAL_16_DIGIT_ID_HERE';

const MANUAL_SIDEBAR_ADS_ENABLED = false;

const ADSENSE_LEFT_SIDEBAR_SLOT_ID = '';

const ADSENSE_RIGHT_SIDEBAR_SLOT_ID = '';

const VALID_PUBLISHER_ID_PATTERN = /^pub-\d{16}$/;
const VALID_CLIENT_ID_PATTERN = /^ca-pub-\d{16}$/;
const VALID_AD_SLOT_PATTERN = /^\d{6,20}$/;

const ADSENSE_CLIENT_ID = VALID_PUBLISHER_ID_PATTERN.test(ADSENSE_PUBLISHER_ID)
  ? `ca-${ADSENSE_PUBLISHER_ID}`
  : '';

const ADSENSE_CONFIGURED =
  VALID_PUBLISHER_ID_PATTERN.test(ADSENSE_PUBLISHER_ID) &&
  VALID_CLIENT_ID_PATTERN.test(ADSENSE_CLIENT_ID) &&
  ADSENSE_PUBLISHER_ID !== 'pub-0000000000000000';

const LEFT_SIDEBAR_SLOT_VALID = VALID_AD_SLOT_PATTERN.test(ADSENSE_LEFT_SIDEBAR_SLOT_ID);
const RIGHT_SIDEBAR_SLOT_VALID = VALID_AD_SLOT_PATTERN.test(ADSENSE_RIGHT_SIDEBAR_SLOT_ID);
const MANUAL_SIDEBAR_ADS_CONFIGURED =
  ADSENSE_CONFIGURED &&
  MANUAL_SIDEBAR_ADS_ENABLED === true &&
  LEFT_SIDEBAR_SLOT_VALID &&
  RIGHT_SIDEBAR_SLOT_VALID;
const GA_MEASUREMENT_ID = 'G-PPMK24W61X';

module.exports = {
  SITE_ORIGIN,
  ADSENSE_PUBLISHER_ID,
  ADSENSE_CLIENT_ID,
  ADSENSE_CONFIGURED,
  VALID_PUBLISHER_ID_PATTERN,
  VALID_CLIENT_ID_PATTERN,
  MANUAL_SIDEBAR_ADS_ENABLED,
  ADSENSE_LEFT_SIDEBAR_SLOT_ID,
  ADSENSE_RIGHT_SIDEBAR_SLOT_ID,
  VALID_AD_SLOT_PATTERN,
  LEFT_SIDEBAR_SLOT_VALID,
  RIGHT_SIDEBAR_SLOT_VALID,
  MANUAL_SIDEBAR_ADS_CONFIGURED,
  GA_MEASUREMENT_ID
};
