const SITE_ORIGIN = 'https://www.ffliveplay.com';
const ADSENSE_PUBLISHER_ID = 'pub-PASTE_REAL_PUBLISHER_ID_HERE';
const ADSENSE_CLIENT_ID = 'ca-pub-PASTE_REAL_PUBLISHER_ID_HERE';
const GA_MEASUREMENT_ID = 'G-PPMK24W61X';

module.exports = {
  SITE_ORIGIN,
  ADSENSE_PUBLISHER_ID,
  ADSENSE_CLIENT_ID,
  GA_MEASUREMENT_ID
};
