const SITE_ORIGIN = 'https://www.ffliveplay.com';

// ======================================================
// OWNER MONETIZATION SETTINGS - EDIT ONLY THIS SECTION
// ======================================================

const ADSENSE_PUBLISHER_ID = 'pub-PASTE_REAL_16_DIGIT_ID_HERE';

const STANDARD_ADSENSE_ENABLED = true;
const AUTO_ADS_ENABLED = true;

const MANUAL_SIDEBAR_ADS_ENABLED = false;

const ADSENSE_LEFT_SIDEBAR_SLOT_ID = '';

const ADSENSE_RIGHT_SIDEBAR_SLOT_ID = '';

// H5 Games Ads requires separate official Google approval/access.
const H5_GAMES_ADS_ACCESS_APPROVED = false;
const H5_GAMES_ADS_ENABLED = false;
const H5_INTERSTITIAL_ADS_ENABLED = false;
const H5_REWARDED_ADS_ENABLED = false;

// Test mode must never be enabled in a production release.
const H5_ADS_TEST_MODE = false;

// Keep a conservative frequency hint.
const H5_AD_FREQUENCY_HINT = '120s';

// Optional preload setting supported by the official API.
const H5_PRELOAD_AD_BREAKS = 'on';

const VALID_PUBLISHER_ID_PATTERN = /^pub-\d{16}$/;
const VALID_CLIENT_ID_PATTERN = /^ca-pub-\d{16}$/;
const VALID_AD_SLOT_PATTERN = /^\d{6,20}$/;
const VALID_H5_FREQUENCY_HINT_PATTERN = /^\d+s$/;

const ADSENSE_CLIENT_ID = VALID_PUBLISHER_ID_PATTERN.test(ADSENSE_PUBLISHER_ID)
  ? `ca-${ADSENSE_PUBLISHER_ID}`
  : '';

const ADSENSE_CONFIGURED =
  VALID_PUBLISHER_ID_PATTERN.test(ADSENSE_PUBLISHER_ID) &&
  VALID_CLIENT_ID_PATTERN.test(ADSENSE_CLIENT_ID) &&
  ADSENSE_PUBLISHER_ID !== 'pub-0000000000000000';

const STANDARD_ADSENSE_CONFIGURED =
  ADSENSE_CONFIGURED &&
  STANDARD_ADSENSE_ENABLED === true;

const LEFT_SIDEBAR_SLOT_VALID = VALID_AD_SLOT_PATTERN.test(ADSENSE_LEFT_SIDEBAR_SLOT_ID);
const RIGHT_SIDEBAR_SLOT_VALID = VALID_AD_SLOT_PATTERN.test(ADSENSE_RIGHT_SIDEBAR_SLOT_ID);
const MANUAL_SIDEBAR_ADS_CONFIGURED =
  STANDARD_ADSENSE_CONFIGURED &&
  MANUAL_SIDEBAR_ADS_ENABLED === true &&
  LEFT_SIDEBAR_SLOT_VALID &&
  RIGHT_SIDEBAR_SLOT_VALID;
const GA_MEASUREMENT_ID = 'G-PPMK24W61X';

const H5_AD_FREQUENCY_HINT_VALID = VALID_H5_FREQUENCY_HINT_PATTERN.test(H5_AD_FREQUENCY_HINT);
const H5_PRELOAD_AD_BREAKS_VALID = H5_PRELOAD_AD_BREAKS === 'on' || H5_PRELOAD_AD_BREAKS === 'auto';
const H5_GAMES_ADS_CONFIGURED =
  STANDARD_ADSENSE_CONFIGURED &&
  H5_GAMES_ADS_ACCESS_APPROVED === true &&
  H5_GAMES_ADS_ENABLED === true &&
  H5_AD_FREQUENCY_HINT_VALID &&
  H5_PRELOAD_AD_BREAKS_VALID;

const H5_INTERSTITIAL_ADS_CONFIGURED =
  H5_GAMES_ADS_CONFIGURED &&
  H5_INTERSTITIAL_ADS_ENABLED === true;

const H5_REWARDED_ADS_CONFIGURED =
  H5_GAMES_ADS_CONFIGURED &&
  H5_REWARDED_ADS_ENABLED === true;

const MONETIZATION_MODE = ADSENSE_CONFIGURED
  ? (H5_GAMES_ADS_CONFIGURED ? 'STANDARD_ADSENSE_AND_H5_READY' : 'STANDARD_ADSENSE_READY')
  : 'PENDING_OWNER_CONFIGURATION';

module.exports = {
  SITE_ORIGIN,
  ADSENSE_PUBLISHER_ID,
  ADSENSE_CLIENT_ID,
  ADSENSE_CONFIGURED,
  STANDARD_ADSENSE_ENABLED,
  STANDARD_ADSENSE_CONFIGURED,
  AUTO_ADS_ENABLED,
  VALID_PUBLISHER_ID_PATTERN,
  VALID_CLIENT_ID_PATTERN,
  MANUAL_SIDEBAR_ADS_ENABLED,
  ADSENSE_LEFT_SIDEBAR_SLOT_ID,
  ADSENSE_RIGHT_SIDEBAR_SLOT_ID,
  VALID_AD_SLOT_PATTERN,
  LEFT_SIDEBAR_SLOT_VALID,
  RIGHT_SIDEBAR_SLOT_VALID,
  MANUAL_SIDEBAR_ADS_CONFIGURED,
  H5_GAMES_ADS_ACCESS_APPROVED,
  H5_GAMES_ADS_ENABLED,
  H5_INTERSTITIAL_ADS_ENABLED,
  H5_REWARDED_ADS_ENABLED,
  H5_ADS_TEST_MODE,
  H5_AD_FREQUENCY_HINT,
  H5_PRELOAD_AD_BREAKS,
  VALID_H5_FREQUENCY_HINT_PATTERN,
  H5_AD_FREQUENCY_HINT_VALID,
  H5_PRELOAD_AD_BREAKS_VALID,
  H5_GAMES_ADS_CONFIGURED,
  H5_INTERSTITIAL_ADS_CONFIGURED,
  H5_REWARDED_ADS_CONFIGURED,
  MONETIZATION_MODE,
  GA_MEASUREMENT_ID
};
